### ISSUE TITLE
Get Error while using this transport

### ISSUE THREAD

**Issue by savinash47** [avens19/winston-sumologic-transport#17]
throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.

versions:
winston-sumologic-transport@3.2.3
winston@3.3.3

**Comment by ray-vgw** [comment]
How are you using the transport?  Can we see the code where you configure the logger?

**Comment by avens19** [comment]
Closing due to age. Please reopen with more details if it's still happening

**Comment by savinash47** [comment]
created new issue with more details.
