### ISSUE TITLE
Documentation of default error handling behavior

### ISSUE THREAD

**Issue by rcollette** [avens19/winston-sumologic-transport#22]
Generally most loggers swallow errors so as not to adversely affect the host application or cause infinite logging loops.

The default behavior for this transport is to throw an unhandled promise rejection when an error occurs, such as receiving an http 429 throttling response from Sumologic.

While this transport provides the onError configuration option for changing this behavior, I believe it would be useful to explain the nature of the default behavior in the README and that it would prevent infrequent but sudden surprises when errors occur.

**Comment by rcollette** [comment]
Two issues with this code
https://github.com/avens19/winston-sumologic-transport/blob/d4341971c39a805c0f32759e92a5b604262d65a5/src/winston-sumologic-transport.ts#L60

A promise is created in a try block without a catch block, which at some point will completely fail to load/run in Node.

`this._promise` is not used in any meaningful way.  The class field can be removed and the call to `_sendLogs()` awaited directly.

**Comment by avens19** [comment]
Thanks for the issue report! this._promise is used in the tests only :). I have pushed a new release [5.0.0](https://github.com/avens19/winston-sumologic-transport/releases/tag/5.0.0) with the error swallowing behaviour
