### ISSUE TITLE
options should be passed down to `super()`, otherwise format doesn't work

### ISSUE THREAD

**Issue by nojvek** [avens19/winston-sumologic-transport#23]
Cannot pass custom format function to sumologic logger even though underlying TransportStream library supports it.

```
    const errorStackFormat = format((info) => {
      console.log('errorStackFormat', { info });
      if (info instanceof Error) {
        info.message = info.stack;
      }
      return info;
    });

    const sumoOptions = {
      url: config.get('sumo:url'),
      meta: { environment: config.get('environment:deploy') },
      level: 'error',
      format: errorStackFormat(),
    };
    logger.add(new SumoLogic(sumoOptions));
  ```

`errorStackFormat` function never gets called.

the deeper issue is that `super()` call should pass options i.e `super(options)` for the format to take effect.

https://github.com/avens19/winston-sumologic-transport/blob/4f005e864f630d498790915f34154b876f7f3e5c/src/winston-sumologic-transport.ts#L34-L37

underlying winston.TransportStream expects Options to be passed in.

https://github.com/winstonjs/winston-transport/blob/8edbd9497391c2aa431d2493862d994be9dbc0d2/index.js#L18

```
const TransportStream = module.exports = function TransportStream(options = {}) {
```

**Comment by avens19** [comment]
Fixed in https://github.com/avens19/winston-sumologic-transport/releases/tag/5.1.0
