### ISSUE TITLE
Get Error while using the transport

### ISSUE THREAD

**Issue by savinash47** [avens19/winston-sumologic-transport#24]
`throw new Error('Invalid transport, must be an object with a log method.');
    ^

Error: Invalid transport, must be an object with a log method.`

at node_modules/winston-transport/legacy.js:18

`const winston = require("winston");
var { SumoLogic } = require('winston-sumologic-transport');

var options = {
    url: "url"
};

winston.add(SumoLogic, options);
winston.debug("Hello, world!");
`

winston@3.7.2
winston-sumologic-transport@5.1.0

**Comment by maddy65** [comment]
I am getting the same error. Is there anyway you have fixed this.

**Comment by avens19** [comment]
Sorry, my README needed to be updated. This has been fixed
