### ISSUE TITLE
Cannot set headers for sourceCategory, sourceName on log request

### ISSUE THREAD

**Issue by aschlumpf** [avens19/winston-sumologic-transport#25]
The transport is missing the ability to set fields such as `sourceCategory` and `sourceName` on the log request. 

These fields exist as options on the sumo logic js SDK which my code base is migrating from in favor of Winston and this transport: https://github.com/SumoLogic/js-sumo-logger/blob/master/src/sumoLogger.js#L72

According to official Sumo documentation, these fields are set as headers on the logging request: https://help.sumologic.com/03Send-Data/Sources/02Sources-for-Hosted-Collectors/HTTP-Source/Upload-Data-to-an-HTTP-Source#supported-http-headers

**Comment by avens19** [comment]
Fixed in [5.2.0](https://github.com/avens19/winston-sumologic-transport/releases/tag/5.2.0)

**Comment by aschlumpf** [comment]
@avens19 I was going to do this but thanks for getting it done so quick!
