### ISSUE TITLE
Doesn't record `DurationMs` when using `winston.profile`

### ISSUE THREAD

**Issue by jmveliz-cps** [avens19/winston-sumologic-transport#30]
When using `winston.profile`, SumoLogic only gets the message without the `DurationMs` field. Thanks.

**Comment by jmveliz-cps** [comment]
Thanks @avens19 for doing the update! I appreciate it! I would suggest to not modify the `message` by adding the duration, this allows `message` to be fixed (making filters easier) and only have `durationMs` to report the value. Thanks!

**Comment by avens19** [comment]
Done! Published as `5.4.1`

**Comment by jmveliz-cps** [comment]
Thanks! I greatly appreciate it!
