### ISSUE TITLE
Can't work with `winston 3.1.0`

### ISSUE THREAD

**Issue by zhaoyi0113** [avens19/winston-sumologic-transport#4]
I am using `winston 3.1.0` but it doesn't compile with below error:

`Type 'SumoLogic' is missing the following properties from type 'TransportStream': writable, writableHighWaterMark, writableLength, _write, and 9 more`

**Comment by avens19** [comment]
In the meantime you can @ts-ignore the .add() line. But honestly it seems that winston changed their transport API and didn't document it very well at all

**Comment by avens19** [comment]
Fixed vis #5
