### ISSUE TITLE
How to handle errors thrown when sending logs

### ISSUE THREAD

**Issue by OlPainless** [avens19/winston-sumologic-transport#7]
Hi,

I'm wondering what the correct approach is to handle errors which occur during sending of logs. For example, if an invalid URL is specified, by default an `UnhandledPromiseRejectionWarning` is issued. 

Is there some way to avoid this and handle the errors properly?

Kind regards,
Andreas

**Comment by avens19** [comment]
https://github.com/avens19/winston-sumologic-transport/releases/tag/3.1.0

Adds onError method

**Comment by huksley** [comment]
Hmm, any change this change released for 1.2.X branch which is winston 2.x compatible?

**Comment by avens19** [comment]
https://github.com/avens19/winston-sumologic-transport/releases/tag/1.3.0

**Comment by Stumpas** [comment]
@avens19 The onErrors works well, but I'm having an issue where it keeps retrying to resend with bad URI. Is there a way to cause it to exit or stop retrying on error?
