### ISSUE TITLE
SumoLogic is a legacy winston transport. Consider upgrading

### ISSUE THREAD

**Issue by Ziggoto** [avens19/winston-sumologic-transport#9]
I just configured this package and then I got this message.

```
SumoLogic is a legacy winston transport. Consider upgrading:
- Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```

**Comment by markhughes** [comment]
@avens19 are you still maintaining this project?

**Comment by avens19** [comment]
@markhughes @Ziggoto 

Sorry guys, this got lost in the shuffle, upgrade on the way

**Comment by avens19** [comment]
It appears that this was already done... What version are you guys using? I'm seeing v3 support added March 2019?

**Comment by Ziggoto** [comment]
@avens19 I had to drop this plugin unfortunately. At the end of the day we came out with another approach
